### ISSUE TITLE
Add HTTP 2.0 support

### ISSUE THREAD

**Issue by miere** [Skullabs/kikaha#146]

**Comment by miere** [comment]
Undertow currently supports HTTP 2.0 setting the ```UndertowOptions.ENABLE_HTTP2``` server option to ```true```. Therefore, it is possible to configure Kikaha to handle HTTP 2 request as shown at the configuration file bellow:

```yml
server:
  undertow:
    server-options:
      ENABLE_HTTP2: true
```
