### ISSUE TITLE
Add SQS connector for the new uWorkers API

### ISSUE THREAD

**Issue by miere** [Skullabs/kikaha#177]

**Comment by miere** [comment]
The just released  2.1.0-alpha3 version closes this issue. How it works?

1. Configure a SQS queue on the AWS SQS Console as described [here](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-create-queue.html)
2. Include the ```kikaha-uworkers-aws-sqs``` on yout project.
3. Configure the AWS credentials and the SQS Queue URL on the ```application.yml```:
```yml
server:
  # default AWS credential is used by the SQS Module
  aws:
    credentials:
      default:
        access-key-id: "access-id"
        secret-access-key: "secret-key"
  # Worker pointing to localhost for test propose
  uworkers:
    # Here is the name of the endpoint
    # This name is used on the source code
    sample-message:
      # How many workers will consume messages from the same SQS queue
      parallelism: 2
      # The SQS queue this endpoint is actually consuming messages
      url: 'https://sqs-*****.amazon.com/****/SampleMessage'

```
4. Create the message class. This class will represent the object send to the SQS Queue:
```java
@Data
public class Message {
  final String content;
}
```
5. Create a Worker class. This class contains a method that will listen for ```Message```s.
```java
@Singleton @Slf4j
public class MessageWorker {

  @Worker( "sample-message" )
  public void consumeMessage( Message message ) {
    log.info( "Received message: " + message );
  }
}
```
6. Create a Worker Reference to send messages to the Queue.
```java
@Singleton @Slf4j
@Path("messages")
public class MessageRestEndpoint {

  @Worker( "sample-message" )
  WorkerRef sampleMessageWorker;

  @POST
  @Consumes(Mimes.PLAIN_TEXT)
  public void sendMessage( String message ) {
     sampleMessageWorker.send( new Message( message ) ); 
  }
}
```

In this sample we just create a REST endpoint that receive messages and forwards it to the SQS queue. Workers were instructed to consume those messages asynchronously. In order to distribute the work load, consider put the implementation on the step 5 on a different application than the one at the 6.
