### ISSUE TITLE
SessionStore configurable mechanism

### ISSUE THREAD

**Issue by miere** [Skullabs/kikaha#178]
The current Kikaha Security module forces developers to create a new SecurityContextFactory to setup a different SessionStore for their application. The intention behind this issue is provide a new mechanism which developers would be able to setup a SessionStore from their `application.yml` files, which is convenient once all other authentication stuffs are configured there already.

My expectation is that users should be able to write an `application.yml` as simple as bellow to setup a different SessionStore to their applications.
```yml
server:
  auth:
    session-store: kikaha.core.module.security.InMemorySessionStore
```
